"""add unique to resume_id in language_skill

Revision ID: 14564538e26f
Revises: 75928644ba8e
Create Date: 2024-10-09 19:04:35.839027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14564538e26f'
down_revision: Union[str, None] = '75928644ba8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'language_skills', ['resume_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'language_skills', type_='unique')
    # ### end Alembic commands ###
