"""add resume_image

Revision ID: 23a8d8e33f6b
Revises: dac48b73d2c3
Create Date: 2024-09-23 20:33:47.852774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a8d8e33f6b'
down_revision: Union[str, None] = 'dac48b73d2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('resume_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'resume_image')
    # ### end Alembic commands ###
