"""add job_applied_for field

Revision ID: 75928644ba8e
Revises: 23a8d8e33f6b
Create Date: 2024-10-07 18:51:34.914698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75928644ba8e'
down_revision: Union[str, None] = '23a8d8e33f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('job_applied_for', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'job_applied_for')
    # ### end Alembic commands ###
