"""update language skils

Revision ID: dac48b73d2c3
Revises: 1a51fdec12d7
Create Date: 2024-09-23 20:28:20.892446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac48b73d2c3'
down_revision: Union[str, None] = '1a51fdec12d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_skills', sa.Column('other_languages', sa.String(), nullable=True))
    op.drop_column('language_skills', 'is_mother_tongue')
    op.drop_column('language_skills', 'proficiency_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_skills', sa.Column('proficiency_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('language_skills', sa.Column('is_mother_tongue', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('language_skills', 'other_languages')
    # ### end Alembic commands ###
