"""add payment id to stritpe payment

Revision ID: f3d981b036e2
Revises: 7b5eb9badd6f
Create Date: 2024-09-18 20:11:32.586679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d981b036e2'
down_revision: Union[str, None] = '7b5eb9badd6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stripe_payments', sa.Column('payment_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_stripe_payments_payment_id'), 'stripe_payments', ['payment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stripe_payments_payment_id'), table_name='stripe_payments')
    op.drop_column('stripe_payments', 'payment_id')
    # ### end Alembic commands ###
